name: 'Slack Project Notifier by Hayuna'

description: 'A GitHub Action to notify a Slack channel with an actionable and minimal message when a card changes project columns.'

branding:
  icon: 'heart'
  color: 'purple'

inputs:
  USERNAME:
    description: 'Username visible in slack notification.'
    required: false
  TEXT:
    description: 'Text visible in slack notification.'
    required: false
  ICON_EMOJI:
    description: 'Emoji visible in slack notification.'
    required: false
  COLOR:
    description: 'Color of notification in slack.'
    required: false
  SLACK_WEBHOOK_URL:
    description: 'Incoming Webhook from Slack.'
    required: true
  PROJECT:
    description: 'GitHub project id from the GitHub API. Set the action to work on only one project. Read console log to retrieve the value.'
    required: false
  TOKEN:
    description: 'Github personal access token, scoped for repository admin.'
    required: true

runs:
  using: 'node12'
  main: 'index.js'
